### ISSUE TITLE
Add support for PKCS#8 RSA key format

### ISSUE THREAD

**Issue by cfouche3005** [QianheYu/headscale-panel#1]
Since Openssl 1.0, keys are generated by default in PKCS#8 format (and are more used in this format), but headscale-panel lacks support of it.

**Comment by QianheYu** [comment]
Now headscale-panel support keys in PKCS#8 format, but still dose not support encrypted PKCS#8. 
I am having some issues with `x509.ParsePKCS8PrivateKey()`, even after decrypting with `x509.DecryptPEMBlock()` it still shows `x509: no DEK-Info header in block`. The code for this is commented out in [util/rsa.go](https://github.com/QianheYu/headscale-panel/blob/main/util/rsa.go).
Do you have any idea why or how to solve this problem?
