### ISSUE TITLE
个人中心无法修改密码

### ISSUE THREAD

**Issue by VMCoud** [QianheYu/headscale-panel#3]
{"code":400,"data":null,"message":"Operate password error"}

**Comment by VMCoud** [comment]
无法添加设备提示{"code":400,"data":null,"message":"Name必须是小写字母"}

**Comment by QianheYu** [comment]
证实以上两个是bug，将在未来的几天内修复

**Comment by VMCoud** [comment]
> 证实以上两个是bug，将在未来的几天内修复

在控制面板创建的用户会关联到headscale吗

**Comment by QianheYu** [comment]
> > 证实以上两个是bug，将在未来的几天内修复
> 
> 在控制面板创建的用户会关联到headscale吗

会的，目前headscale-panel与headscale在postgresql中共用数据库中的用户表。
不过由于我是应届自学转行过来的经验有限，我不知道这样做是否合理。

**Comment by QianheYu** [comment]
如果您有更好的方法，欢迎讨论和学习

**Comment by QianheYu** [comment]
目前上述bug已修复，需要后端需要升级到v0.1.4及以上，前端升级到v0.1.3及以上
