### ISSUE TITLE
[功能请求]将身份验证的链接重定向到headscale-panel-ui

### ISSUE THREAD

**Issue by VMCoud** [QianheYu/headscale-panel#6]
将身份验证的链接重定向到headscale-panel-ui，登录后自动关联设备到登录用户

**Comment by QianheYu** [comment]
该功能以通过的OIDC实现，用户在tailscale客户端上设置好服务端地址后，在tailscale客户端登陆时会跳转到web前端的连接页面，点击连接后加入到tailnet并关联已登陆用户，若web端没有登陆则会要求先登陆然后跳转到连接页面。但该过程需要在config.yaml配置文件中设置。
这里是我使用的设置在此作为示例：
<img width="812" alt="image" src="https://github.com/QianheYu/headscale-panel/assets/112762030/9f7087af-1bef-4519-886a-c29d74436f23">
issuer: 是headscale-panel服务端
authorize: 是前端位置，如果您使用headscale-panel-ui仅需要更改域名即可
client_id和client_secret与headscale后端的oidc中设置保持一致即可

**Comment by QianheYu** [comment]
不知道我的回复是否是你想要的，如果不是麻烦您在详细描述一下

**Comment by VMCoud** [comment]
刚刚测试了，是这个功能
